services:
  postgres_server:
    image: postgres:16.0
    environment:
      POSTGRES_DB: MyAppDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
    networks:
      - app-network
    
  api:
    image: darkexist/datingapp-api:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres_server;Port=5432;Database=MyAppDb;Username=postgres;Password=test
      - EmailSettings__Username=datingappbot@mail.ru
      - EmailSettings__Password=f9ApGSUFHL28bGkeurf6
      - JwtOptions__SecretKey=your-super-secret-key-here-min-32-chars
      - JwtOptions__ExpiresInMinutes=60
    depends_on:
      - postgres_server
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge