import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/ui";

const raleway = Raleway({
    variable: "--font-main",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${raleway.variable} antialiased overflow-hidden flex flex-col items-center`}>
                <div className="w-full flex py-[10px] justify-center bg-(image:--bg-gradient)">
                    <div className="w-7xl">
                        <Header />
                    </div>
                </div>
                <div className="container max-w-7xl">{children}</div>
            </body>
        </html>
    );
}
