// <auto-generated />
using System;
using System.Numerics;
using DatingApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatingApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AchievementProfile", b =>
                {
                    b.Property<Guid>("AchievementsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("AchievementsId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("AchievementProfile");
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d395bac9-476c-4d1c-893c-59ac72f3bfc3"),
                            Description = "Успешная регистрация в сервисе",
                            Name = "0days"
                        },
                        new
                        {
                            Id = new Guid("1ddd25d2-3813-4301-b7a7-91ce30d79666"),
                            Description = "Стаж 1 месяц",
                            Name = "30days"
                        },
                        new
                        {
                            Id = new Guid("29692dab-526b-46ee-a76b-b0e1bfb11a85"),
                            Description = "Стаж 1 год",
                            Name = "365days"
                        },
                        new
                        {
                            Id = new Guid("5c613232-a6ca-4ee5-89b7-7d82c4a9fb3d"),
                            Description = "Поставить первый лайк",
                            Name = "1likesent"
                        },
                        new
                        {
                            Id = new Guid("dfe6a248-d9f3-4d24-ba92-e5bd51d636b8"),
                            Description = "Поставить 100 лайков",
                            Name = "100likesent"
                        },
                        new
                        {
                            Id = new Guid("8ea9c875-a26b-40da-99c3-9a7ae084ef0a"),
                            Description = "Поставить первый дизлайк",
                            Name = "1dislikesent"
                        },
                        new
                        {
                            Id = new Guid("13de6946-df16-45e0-b3ef-151fed66dd4c"),
                            Description = "Поставить 100 дизлайков",
                            Name = "100dislikesent"
                        },
                        new
                        {
                            Id = new Guid("65c7a89d-eb8a-495a-b165-837a696472c8"),
                            Description = "Получить первый лайк",
                            Name = "1likegot"
                        },
                        new
                        {
                            Id = new Guid("c0b8f363-47de-46a1-a0b5-b927f6e0f37a"),
                            Description = "Получить 100 лайков",
                            Name = "100likegot"
                        },
                        new
                        {
                            Id = new Guid("a8d62703-b2a3-4141-abbc-276c62829969"),
                            Description = "Получить первый дизлайк",
                            Name = "1dislikegot"
                        },
                        new
                        {
                            Id = new Guid("55d18c79-209c-45b9-892a-d83926ddbfca"),
                            Description = "Получить 100 дизлайков",
                            Name = "100dislikegot"
                        });
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SlaveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Actions", (string)null);
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Hobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hobbies", (string)null);
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ownerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("predictedId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Predictions", (string)null);
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "Value");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bcca34e-96f9-4587-9d40-9cb0debfcf5a"),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("8dde508d-6d11-4b9f-8db7-28eeb58117a6"),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("d7775f8c-3e4d-4fc0-a51d-8736178b352f"),
                            Name = "moderator"
                        });
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HobbyProfile", b =>
                {
                    b.Property<Guid>("HobbiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("HobbiesId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("HobbyProfile");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("Users_Roles", (string)null);
                });

            modelBuilder.Entity("AchievementProfile", b =>
                {
                    b.HasOne("DatingApp.Domain.Entities.Achievement", null)
                        .WithMany()
                        .HasForeignKey("AchievementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatingApp.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.Profile", b =>
                {
                    b.HasOne("DatingApp.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("DatingApp.Domain.Entities.Profile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("DatingApp.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HobbyProfile", b =>
                {
                    b.HasOne("DatingApp.Domain.Entities.Hobby", null)
                        .WithMany()
                        .HasForeignKey("HobbiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatingApp.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("DatingApp.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatingApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatingApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
